### ISSUE TITLE
Master test runner spell

### ISSUE THREAD

**Issue by coffeeorgreentea** [Oneirocom/Magick#985] opened 2023-06-06 17:34 UTC

**Comment by Knar33** [comment] 2023-06-07 15:26
- Clean up the test spells and make sure we have full coverage
- Create a single spell that runs all of the test spells
- Export these into their own project (right now the test spells are jumbled in with all of my other spells)
- Get these test spells somewhere in source control

**Comment by Knar33** [comment] 2023-06-13 23:17
Duplicate of #1033

**Closed by Knar33** 2023-06-13 23:17 UTC
