### ISSUE TITLE
Engine imported directly into Next.js project

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#407] opened 2023-03-14 08:16 UTC

**Comment by michaelsharpe** [comment] 2023-03-14 17:38
@lalalune Can we get some clarification on this one?  Not sure what it means.

**Comment by lalalune** [comment] 2023-03-17 04:30
The goal is to make it so we can import our editor directly into a Next.js project, the problem is that the react-router is not compatible with next-router, but if we shift our exports around and import directly into the pages it'll be fine

**Comment by coffeeorgreentea** [comment] 2023-04-25 18:48
closed as dupe of #328

**Closed** 2023-04-25 18:48 UTC
